[build]
  command = "echo No build for this site, we are living on the edge"
  publish = "public"


[[edge_functions]]
  path = "/h5_campaign"
  function = "h5_campaign-missions"

[[edge_functions]]
  path = "/h5_appearance"
  function = "h5_appearance"